Repository CaC-Fullstack-NodeJS/Hood_Barber, pull requests merged in 2024-05, with the labels that each got.

#1 update
  assets/barberia.ico
  assets/cortes1.jpg
  assets/cortes2.jpg
  assets/logo.png
  index.html
  pages/calendar.html
  pages/where.html
  src/css/calendar.css
  src/css/styles.css
  src/js/calendar.js
Labels: enhancement

#4 Facundo
  assets/cortes/Buzz Cut.jpg
  assets/cortes/Slicked Back.jpg
  assets/cortes/Top Knot.jpg
  assets/cortes/mullet.jpg
  pages/calendar.html
  pages/haircuts.html
  pages/where.html
  src/css/haircuts.css
Labels: enhancement

#10 ordeno algo de estructura, replico header y footer. subo actualizacio…
  README.md
  assets/img/AdobeColor-CodoaCodo Node.js 2024.jpeg
  assets/img/barberia.ico
  assets/img/cortes1.jpg
  assets/img/cortes2.jpg
  assets/img/logo.png
  assets/img/logoNode.svg
  index.html
  pages/about.html
  pages/calendar.html
  pages/haircuts.html
  pages/where.html
  src/css/calendar.css
  src/css/style.css
  src/css/styles.css
  src/js/calendar.js
  src/js/script.js
Labels: Working

#15 borro signo >
  pages/calendar.html
  pages/haircuts.html
Labels: Working

#17 Manu
  index.html
  src/css/style.css
Labels: Working, improvements

#20 Manu
  index.html
  src/css/style.css
  src/img/logo fondo transp.png
  src/img/novedades/pexels-cottonbro-3998429.jpg
  src/img/novedades/pexels-thgusstavo-1804638.jpg
  src/img/novedades/pexels-thgusstavo-1813346.jpg
  src/img/novedades/pexels-thgusstavo-1836983.jpg
  src/img/novedades/pexels-thgusstavo-2040189.jpg
  src/img/novedades/pexels-thgusstavo-2068672.jpg
  src/img/novedades/pexels-thgusstavo-2076930.jpg
  src/img/novedades/pexels-thgusstavo-2521978.jpg
  src/img/novedades/pexels-thgusstavo-2809652.jpg
  src/img/pexels-andrew-beatson-2114196-3742709.jpg
  src/img/servicios/1.jpg
  src/img/servicios/2.jpg
  src/img/servicios/3.jpg
  src/img/servicios/4.jpg
  src/img/servicios/5.jpg
  src/img/servicios/6.jpg
Labels: improvements

#21 suboo act de enlaces y css
  index.html
  pages/about.html
  pages/calendar.html
  pages/haircuts.html
  src/css/style.css
Labels: improvements

#22 Manu
  index.html
  src/css/style.css
Labels: improvements

#23 actualizo mejoras grales
  index.html
  pages/about.html
  pages/calendar.html
  pages/contact.html
  pages/haircuts.html
Labels: improvements

#24 localit
  index.html
  pages/about.html
  pages/calendar.html
  pages/contact.html
  pages/haircuts.html
Labels: improvements

#25 update
  index.html
  src/css/style.css
  src/js/script.js
Labels: improvements

#28 Manu
  index.html
  src/css/style.css
  src/img/logo vicrofama.png
Labels: improvements

#29 Rodri
  assets/img/2-removebg-preview.png
  assets/img/logo vicrofama.png
  pages/about.html
  pages/contact.html
  src/css/style.css
  src/js/contact.js
Labels: Working, improvements

#30 Cambios para el responsive
  src/css/style.css
Labels: improvements

#31 cambio de imagenes a svg
  index.html
  src/img/2-removebg-preview.svg
  src/img/barberia.svg
  src/img/cortes1.svg
  src/img/cortes2.svg
  src/img/logo.svg
  src/img/logo_fondo_transp.svg
  src/img/logo_vicrofama.svg
  src/img/novedades/1.svg
  src/img/novedades/2.svg
  src/img/novedades/3.svg
  src/img/novedades/4.svg
  src/img/novedades/5.svg
  src/img/novedades/6.svg
  src/img/novedades/7.svg
  src/img/novedades/8.svg
  src/img/novedades/9.svg
  src/img/servicios/1.svg
  src/img/servicios/2.svg
  src/img/servicios/3.svg
  src/img/servicios/4.svg
  src/img/servicios/5.svg
  src/img/servicios/6.svg
Labels: improvements

#32 actualizo header
  assets/img/logo_vicrofama.svg
  index.html
  pages/about.html
  pages/calendar.html
  pages/contact.html
  pages/haircuts.html
  src/css/style.css
Labels: improvements

#33 verificado validatorw3
  index.html
  pages/about.html
  pages/calendar.html
  pages/contact.html
  pages/haircuts.html
  src/css/style.css
Labels: help wanted, improvements

#35 cambios actualizados
  src/css/style.css
Labels: Working, improvements

#38 Victoria
  pages/about.html
  pages/calendar.html
  pages/contact.html
  pages/haircuts.html
Labels: improvements

#39 validator
  index.html
  pages/about.html
  pages/calendar.html
  pages/contact.html
  pages/haircuts.html
Labels: improvements

#42 agrego selector en calendr
  pages/calendar.html
  src/css/style.css
  src/js/calendar.js
Labels: improvements

#44 delete css
  src/css/contact_About.css
Labels: improvements

#45 validator contact
  pages/contact.html
Labels: improvements
